[UX2.0] Adds Policy Objects Profile Parcels - Part 1
CiscoDevNet/terraform-provider-sdwan pull request #264
Opened 2024-06-07 09:40 UTC by seconroy

### Description

**DO NOT MERGE** - You can only have one policy object feature profile for unable to properly test as prerequisites fails

Adds the following Policy Objects profile parcel resource and data source:
- class
- tloc
- color
- data-ipv6-prefix
- data-prefix
- expanded-community
- ext-community
- ipv6-prefix
- prefix
- mirror
- policer

### Types of Changes

* [x] New feature (non-breaking change which adds functionaality)
* [ ] Bug fix (non-breaking change which fixes an issue)
* [ ] Breaking change (fix or feature that would cause existing functionality to change)
* [ ] Build/CI change
* [ ] Code quality improvement/refactoring/documentation (no functional changes)

### Checklist

* [x] My code follows the code style of this project
* [x] I have added tests to cover my changes
* [ ] All new and existing tests pass locally

2024-07-18 10:55 UTC, tzarski0 requested changes

2024-07-18 10:55 UTC, tzarski0 commented on gen/definitions/profile_parcels/policy_object_color.yaml
> +name: Policy Object Color
Rename to "Policy Object Color List"

2024-07-18 10:55 UTC, tzarski0 commented on gen/definitions/profile_parcels/policy_object_data_ipv6_prefix.yaml
> +name: Policy Object Data IPv6 Prefix
Rename to "Policy Object Data IPv6 Prefix List"

2024-07-18 10:55 UTC, tzarski0 commented on gen/definitions/profile_parcels/policy_object_data_prefix.yaml
> +name: Policy Object Data Prefix
Rename to "Policy Object Data IPv4 Prefix List"

2024-07-18 10:55 UTC, tzarski0 commented on gen/definitions/profile_parcels/policy_object_expanded_community.yaml
> +name: Policy Object Expanded Community
Rename to "Policy Object Expanded Community List"

2024-07-18 10:55 UTC, tzarski0 commented on gen/definitions/profile_parcels/policy_object_extended_community.yaml
> +name: Policy Object Extended Community
Rename to "Policy Object Extended Community List"

2024-07-18 10:55 UTC, tzarski0 commented on gen/definitions/profile_parcels/policy_object_ipv6_prefix.yaml
> +name: Policy Object IPv6 Prefix
Rename to "Policy Object IPv6 Prefix List"

2024-07-18 10:55 UTC, tzarski0 commented on gen/definitions/profile_parcels/policy_object_prefix.yaml
> +name: Policy Object Prefix
Rename to "Policy Object IPv4 Prefix List"

2024-07-18 10:55 UTC, tzarski0 commented on gen/definitions/profile_parcels/policy_object_tloc.yaml
> +name: Policy Object TLOC
Rename to "Policy Object TLOC List"

2024-07-18 10:55 UTC, tzarski0 commented on gen/definitions/profile_parcels/policy_object_ipv6_prefix.yaml
> +    - model_name: leRangePrefixLength
should we change it to just "le" to match what we've had for UX1.0 ipv6 prefix-list?

2024-07-18 10:55 UTC, tzarski0 commented on gen/definitions/profile_parcels/policy_object_ipv6_prefix.yaml
> +    - model_name: geRangePrefixLength
should we change it to just "ge" to match what we've had for UX1.0 ipv6 prefix-list?

2024-07-18 10:55 UTC, tzarski0 commented on gen/definitions/profile_parcels/policy_object_prefix.yaml
> +    - model_name: leRangePrefixLength
should we change it to just "le" to match what we've had for UX1.0 ipv4 prefix-list?

2024-07-18 10:55 UTC, tzarski0 commented on gen/definitions/profile_parcels/policy_object_prefix.yaml
> +    - model_name: geRangePrefixLength
should we change it to just "ge" to match what we've had for UX1.0 ipv4 prefix-list?

2024-07-18 10:55 UTC, tzarski0 commented on gen/definitions/profile_parcels/policy_object_tloc.yaml
> +    - model_name: tloc
should we add "tf_name: tloc_ip" to match what we've had for UX1.0 tloc-list?

2024-07-18 10:55 UTC, tzarski0 commented on gen/definitions/profile_parcels/policy_object_policer.yaml
> +      tf_name: select_value
seems not correct. Should we change "tf_name: select_value" to "tf_name: exceed_action"?

2024-08-29 06:01 UTC, danischm approved these changes

2024-08-29 06:02 UTC, merged