[UX2.0] Add OSPF & OSPFv3 Profile Parcels
CiscoDevNet/terraform-provider-sdwan pull request #308
Opened 2024-08-24 13:12 UTC by seconroy

### Description

Adds the following Profile Parcel resources and data sources:
- Transport Routing/OSPF
- Transport Routing/OSPFv3/IPv4
- Transport Routing/OSPFv3/IPv6
- Service Routing/OSPF
- Service Routing/OSPFv3/IPv4
- Service Routing/OSPFv3/IPv6

### Types of Changes

* [x] New feature (non-breaking change which adds functionaality)
* [ ] Bug fix (non-breaking change which fixes an issue)
* [ ] Breaking change (fix or feature that would cause existing functionality to change)
* [ ] Build/CI change
* [ ] Code quality improvement/refactoring/documentation (no functional changes)

### Checklist

* [x] My code follows the code style of this project
* [x] I have added tests to cover my changes
* [x] All new and existing tests pass locally

2024-08-28 10:44 UTC, tzarski0 requested changes

2024-08-28 10:44 UTC, tzarski0 commented on gen/definitions/profile_parcels/service_routing_ospf.yaml
> +      - model_name: type
tf_name: authentication_type

2024-08-28 10:44 UTC, tzarski0 commented on gen/definitions/profile_parcels/service_routing_ospfv3_ipv4.yaml
> +    tf_name: distance_for_external_routes
"distance_external"

2024-08-28 10:44 UTC, tzarski0 commented on gen/definitions/profile_parcels/service_routing_ospfv3_ipv4.yaml
> +    tf_name: distance_for_inter_area_routes
distance_inter_area

2024-08-28 10:44 UTC, tzarski0 commented on gen/definitions/profile_parcels/service_routing_ospfv3_ipv4.yaml
> +    tf_name: distance_for_intra_area_routes
distance_intra_area

2024-08-28 10:44 UTC, tzarski0 commented on gen/definitions/profile_parcels/service_routing_ospfv3_ipv4.yaml
> +  - model_name: originate
Would add "tf_name: default_information_originate"

2024-08-28 10:44 UTC, tzarski0 commented on gen/definitions/profile_parcels/service_routing_ospfv3_ipv4.yaml
> +  - model_name: always
Would add "tf_name: default_information_originate_always"

2024-08-28 10:44 UTC, tzarski0 commented on gen/definitions/profile_parcels/service_routing_ospfv3_ipv4.yaml
> +  - model_name: metric
Would add "tf_name: default_information_originate_metric"

2024-08-28 10:44 UTC, tzarski0 commented on gen/definitions/profile_parcels/service_routing_ospfv3_ipv4.yaml
> +  - model_name: metricType
Would add "tf_name: default_information_originate_metric_type"

2024-08-28 10:44 UTC, tzarski0 commented on gen/definitions/profile_parcels/service_routing_ospfv3_ipv4.yaml
> +    tf_name: spf_calculation_deplay
typo, should be "spf_calculation_delay"

2024-08-28 10:44 UTC, tzarski0 commented on gen/definitions/profile_parcels/service_routing_ospfv3_ipv4.yaml
> +    tf_name: initial_hold_time
spf_initial_hold_time

2024-08-28 10:44 UTC, tzarski0 commented on gen/definitions/profile_parcels/service_routing_ospfv3_ipv4.yaml
> +    tf_name: maximum_hold_time
spf_maximum_hold_time

2024-08-28 10:44 UTC, tzarski0 commented on gen/definitions/profile_parcels/service_routing_ospf.yaml
> +    - model_name: dia
tf_name: nat_dia

2024-08-28 10:44 UTC, tzarski0 commented on gen/definitions/profile_parcels/service_routing_ospfv3_ipv4.yaml
> +      tf_name: enable_nat_dia
Change here to "nat_dia" to have it in line with OSPFv2

2024-08-28 10:44 UTC, tzarski0 commented on gen/definitions/profile_parcels/service_routing_ospfv3_ipv4.yaml
> +    tf_name: router_lsa_on_startu_p_time
typo, should be router_lsa_on_startup_time

2024-08-28 10:44 UTC, tzarski0 commented on gen/definitions/profile_parcels/service_routing_ospfv3_ipv4.yaml
> +      - model_name: ifName
tf_name: name

2024-08-28 10:44 UTC, tzarski0 commented on gen/definitions/profile_parcels/service_routing_ospfv3_ipv4.yaml
> +        tf_name: interface_cost
we could remove that and leave it as "cost"

2024-08-28 10:44 UTC, tzarski0 commented on gen/definitions/profile_parcels/service_routing_ospfv3_ipv4.yaml
> +        tf_name: ospf_network_type
"network_type"

2024-08-28 10:44 UTC, tzarski0 commented on gen/definitions/profile_parcels/service_routing_ospfv3_ipv4.yaml
> +      - model_name: authType
tf_name: authentication_type

2024-08-28 10:44 UTC, tzarski0 commented on gen/definitions/profile_parcels/service_routing_ospfv3_ipv4.yaml
> +        data_path: [authenticationConfig]
tf_name: authentication_spi

2024-08-28 10:44 UTC, tzarski0 commented on gen/definitions/profile_parcels/service_routing_ospfv3_ipv4.yaml
> +      - model_name: authKey
tf_name: authentication_key

2024-08-28 10:44 UTC, tzarski0 commented on gen/definitions/profile_parcels/service_routing_ospf.yaml
> +        data_path: [address]
In OSPFv3 IPv4 we just have "address/mask" here we have "ipAddress/subnetMask" - we should align this in both, not sure which option is better

2024-08-28 10:44 UTC, tzarski0 commented on gen/definitions/profile_parcels/service_routing_ospfv3_ipv6.yaml
> +    tf_name: distance_for_external_routes
distance_external

2024-08-28 10:44 UTC, tzarski0 commented on gen/definitions/profile_parcels/service_routing_ospfv3_ipv6.yaml
> +    tf_name: distance_for_inter_area_routes
distance_inter_area

2024-08-28 10:44 UTC, tzarski0 commented on gen/definitions/profile_parcels/service_routing_ospfv3_ipv6.yaml
> +    tf_name: distance_for_intra_area_routes
distance_intra_area

2024-08-28 10:44 UTC, tzarski0 commented on gen/definitions/profile_parcels/service_routing_ospfv3_ipv6.yaml
> +  - model_name: originate
Would add "tf_name: default_information_originate"

2024-08-28 10:44 UTC, tzarski0 commented on gen/definitions/profile_parcels/service_routing_ospfv3_ipv6.yaml
> +  - model_name: always
Would add "tf_name: default_information_originate_always"

2024-08-28 10:44 UTC, tzarski0 commented on gen/definitions/profile_parcels/service_routing_ospfv3_ipv6.yaml
> +  - model_name: metric
Would add "tf_name: default_information_originate_metric"

2024-08-28 10:44 UTC, tzarski0 commented on gen/definitions/profile_parcels/service_routing_ospfv3_ipv6.yaml
> +  - model_name: metricType
Would add "tf_name: default_information_originate_metric_type"

2024-08-28 10:44 UTC, tzarski0 commented on gen/definitions/profile_parcels/service_routing_ospfv3_ipv6.yaml
> +    tf_name: spf_calculation_deplay
typo, should be "spf_calculation_delay"

2024-08-28 10:44 UTC, tzarski0 commented on gen/definitions/profile_parcels/service_routing_ospfv3_ipv6.yaml
> +    tf_name: initial_hold_time
spf_initial_hold_time

2024-08-28 10:44 UTC, tzarski0 commented on gen/definitions/profile_parcels/service_routing_ospfv3_ipv6.yaml
> +    tf_name: maximum_hold_time
spf_maximum_hold_time

2024-08-28 10:44 UTC, tzarski0 commented on gen/definitions/profile_parcels/service_routing_ospfv3_ipv6.yaml
> +    tf_name: router_lsa_on_startu_p_time
typo, should be router_lsa_on_startup_time

2024-08-28 10:44 UTC, tzarski0 commented on gen/definitions/profile_parcels/service_routing_ospfv3_ipv6.yaml
> +      - model_name: ifName
tf_name: name

2024-08-28 10:44 UTC, tzarski0 commented on gen/definitions/profile_parcels/service_routing_ospfv3_ipv6.yaml
> +        tf_name: interface_cost
we could remove that and leave it as "cost"

2024-08-28 10:44 UTC, tzarski0 commented on gen/definitions/profile_parcels/service_routing_ospfv3_ipv6.yaml
> +        tf_name: ospf_network_type
"network_type"

2024-08-28 10:44 UTC, tzarski0 commented on gen/definitions/profile_parcels/service_routing_ospfv3_ipv6.yaml
> +      - model_name: authType
tf_name: authentication_type

2024-08-28 10:44 UTC, tzarski0 commented on gen/definitions/profile_parcels/transport_routing_ospf.yaml
> +    - model_name: adType
tf_name: type

2024-08-28 10:44 UTC, tzarski0 commented on gen/definitions/profile_parcels/transport_routing_ospfv3_ipv4.yaml
> +        tf_name: interface_cost
we could remove that and leave it as "cost"

2024-08-29 06:14 UTC, danischm approved these changes

2024-08-29 06:16 UTC, merged