[UX2.0] Adds Policy Objects Profile Parcels - Part 2
CiscoDevNet/terraform-provider-sdwan pull request #310
Opened 2024-08-29 13:03 UTC by seconroy

### Description

Also adds the following Policy Objects profile parcel resource and data source:
- App Probe
- As Path
- VPN Group
- Security Data IP Prefix
- Security FQDN
- Security Geo Location
- Security IPS Signature
- Security Local Domain
- Security Port
- Security Scalable Group Tag
- Security Url List
- Preferred Color Group
- Security Identity
- Security Localapp
- Standard Community

### Types of Changes

* [x] New feature (non-breaking change which adds functionaality)
* [ ] Bug fix (non-breaking change which fixes an issue)
* [ ] Breaking change (fix or feature that would cause existing functionality to change)
* [ ] Build/CI change
* [ ] Code quality improvement/refactoring/documentation (no functional changes)

### Checklist

* [x] My code follows the code style of this project
* [x] I have added tests to cover my changes
* [ ] All new and existing tests pass locally

2024-09-02 20:12 UTC, tzarski0 requested changes
I'm not sure if all comments make sense but I was trying to align it with: UX1.0 policy objects, UX2.0 policy objects we added in part 1 PR and UX2.0 names in UI.

2024-09-02 20:12 UTC, tzarski0 commented on gen/definitions/profile_parcels/policy_object_security_ips_signature.yaml
> +name: Policy Object Security IPs Signature
Policy Object Security IPS Signature List (it's IPS for Intrusion Prevention System that's why it should be all capital).

2024-09-02 20:12 UTC, tzarski0 commented on gen/definitions/profile_parcels/policy_object_security_localapp.yaml
> +name: Policy Object Security Localapp
Policy Object Security Local Application List

2024-09-02 20:12 UTC, tzarski0 commented on gen/definitions/profile_parcels/policy_object_security_localdomain.yaml
> +name: Policy Object Security Localdomain
Policy Object Security Local Domain List

2024-09-02 20:12 UTC, tzarski0 commented on gen/definitions/profile_parcels/policy_object_security_localdomain.yaml
> +    - model_name: nameServer
tf_name: local_domain

2024-09-02 20:12 UTC, tzarski0 commented on gen/definitions/profile_parcels/policy_object_security_port.yaml
> +name: Policy Object Security Port
Policy Object Security Port List

2024-09-02 20:12 UTC, tzarski0 commented on gen/definitions/profile_parcels/policy_object_security_scalable_group_tag.yaml
> +name: Policy Object Security Scalable Group Tag
Policy Object Security Scalable Group Tag List

2024-09-02 20:12 UTC, tzarski0 commented on gen/definitions/profile_parcels/policy_object_security_identity.yaml
> +name: Policy Object Security Identity
Policy Object Security Identity List

2024-09-02 20:12 UTC, tzarski0 commented on gen/definitions/profile_parcels/policy_object_security_urllist.yaml
> +name: Policy Object Security URLlist
Policy Object Security URL List

2024-09-02 20:12 UTC, tzarski0 commented on gen/definitions/profile_parcels/policy_object_standard_community.yaml
> +name: Policy Object Standard Community
Policy Object Standard Community List

2024-09-03 07:07 UTC, seconroy commented on gen/definitions/profile_parcels/policy_object_app_probe.yaml
> +    - model_name: map
With the current implementation this is to maintain the structure the API expects

2024-09-09 07:23 UTC, tzarski0 approved these changes

2024-09-09 09:08 UTC, danischm approved these changes

2024-09-09 09:09 UTC, merged