[UX2.0] Adds IPv4 and IPv6 ACL Profile Parcels
CiscoDevNet/terraform-provider-sdwan pull request #317
Opened 2024-09-03 10:19 UTC by seconroy

### Description

Adds the following Profile Parcel resources and data sources:
- Transport acl-ipv4
- Transport acl-ipv6
- Service acl-ipv4
- Service acl-ipv6

### Types of Changes

* [x] New feature (non-breaking change which adds functionaality)
* [ ] Bug fix (non-breaking change which fixes an issue)
* [ ] Breaking change (fix or feature that would cause existing functionality to change)
* [ ] Build/CI change
* [ ] Code quality improvement/refactoring/documentation (no functional changes)

### Checklist

* [x] My code follows the code style of this project
* [x] I have added tests to cover my changes
* [x] All new and existing tests pass locally

2024-10-16 13:37 UTC, tzarski0 requested changes
I've just commented gen/definitions/profile_parcels/service_ipv4_acl.yaml but same comments apply to all ACLs.

2024-10-16 13:37 UTC, tzarski0 commented on gen/definitions/profile_parcels/service_ipv4_acl.yaml
> +        tf_name: accept_counter_name
either make it "counter_name" on condition that we have accept or call it "accept_counter_name" (if first option not possible)

2024-10-16 13:37 UTC, tzarski0 commented on gen/definitions/profile_parcels/service_ipv4_acl.yaml
> +        tf_name: accept_log
either make it "log" on condition that we have accept or call it "accept_log" (if first option not possible)

2024-10-16 13:37 UTC, tzarski0 commented on gen/definitions/profile_parcels/service_ipv4_acl.yaml
> +        tf_name: drop_counter_name
either make it "counter_name" on condition that we have drop or call it "drop_counter_name" (if first option not possible)

2024-10-16 13:37 UTC, tzarski0 commented on gen/definitions/profile_parcels/service_ipv4_acl.yaml
> +        tf_name: drop_log
either make it "log" on condition that we have drop or call it "drop_log" (if first option not possible)

2024-10-16 13:39 UTC, tzarski0 commented on gen/definitions/profile_parcels/service_ipv4_acl.yaml
> +    # - model_name: baseAction
I think this is already fixed right?

2024-10-16 13:41 UTC, seconroy commented on gen/definitions/profile_parcels/service_ipv4_acl.yaml
> +    # - model_name: baseAction
Yes, this has already been uncommented

2024-10-16 20:16 UTC, tzarski0 commented on gen/definitions/profile_parcels/service_ipv4_acl.yaml
> +      tf_name: conditions
@seconroy can we also change this in all 4 ACLs to "match_entries"? This is the name we've used in UX1.0 across all policies and I also see we are using "match_entries" already for UX2.0 route policy so I would rather keep this consistent. Would be good also to align this in application_priority_traffic_policy and change current "tf_name: matches" to "tf_name: match_entries"

2024-10-18 07:44 UTC, danischm approved these changes

2024-10-18 07:44 UTC, merged