[UX2.0] Resolve Issue #296
CiscoDevNet/terraform-provider-sdwan pull request #350
Opened 2024-10-15 11:23 UTC by seconroy

### Description

Resolves Issues #296

### Types of Changes

* [ ] New feature (non-breaking change which adds functionaality)
* [x] Bug fix (non-breaking change which fixes an issue)
* [ ] Breaking change (fix or feature that would cause existing functionality to change)
* [ ] Build/CI change
* [ ] Code quality improvement/refactoring/documentation (no functional changes)

### Checklist

* [x] My code follows the code style of this project
* [x] I have added tests to cover my changes
* [x] All new and existing tests pass locally

2024-10-18 08:17 UTC, danischm requested changes
It looks like SD-WAN manager always includes `unsupported_features` in the GET payload, even if it is set to null. To be consist, we don't want TF users to configure empty lists, but rather omit or set it to null. In this case we should therefore make sure that we translate an empty list in the GET response to a null value in state instead of asking users to configure an empty list.

2024-10-22 09:44 UTC, tzarski0 commented
@seconroy could you please change it as per Daniel's comment?

2025-04-10 10:50 UTC, tzarski0 commented
@seconroy I think we can close this PR as the issue we were trying to solve is no longer happening in the newest provider version?

2025-04-10 10:52 UTC, seconroy commented
@tzarski0 Perfect. I will this then and if the issue reoccurs we can have another look at it

2025-04-10 10:52 UTC, closed without merging